version: '3'
services:
  jwt:
    # Build a docker image from Dockerfile in the same directory
    build:
      context: .
      dockerfile: Dockerfile
    # Give a name to the docker container
    container_name: js-create-jwt_ctr
    # Fetch an environment variable
    environment:
      JWT_SECRET: ${JWT_SECRET}
