name: js-create-jwt

on:
  push:
    branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run:
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: build the docker image
        run: docker build --file Dockerfile -t ${{secrets.DOCKER_USERNAME}}/js-create-jwt:$(date +%s) .
      - name: push to docker registry
        run: docker push ${{secrets.DOCKER_USERNAME}}/js-create-jwt
